<template>
  <div class="flex justify-center py-10">
    <div class="prose lg:prose-xl">
      <h1>Privacy Policy</h1>
    </div>
  </div>
  <div class="flex justify-center">
    <div class="pb-8 prose">
      <p><strong>Last updated:</strong> October 31st, 2023</p>

      <p>
        Welcome to Powerful Questions. This Privacy Policy outlines how we collect,
        use, and disclose information through the Website. Please read this
        policy carefully to understand our practices regarding your information.
      </p>

      <p>
        Your privacy is important to us. It is Spero Autem LLCs&#39; policy to
        respect your privacy and comply with any applicable law and regulation
        regarding any personal information we may collect about you, including
        across our website,
        <a href="https://powerful-questions.com">Powerful-Questions.com</a>, and other sites we own
        and operate.
      </p>

      <h2>Information We Collect</h2>

      <ul>
        <li>
          <strong>Cookies and Similar Technologies:</strong> We use cookies and
          similar technologies to analyze user behavior and improve the
          functionality of our Website. Google Analytics is used to analyze
          traffic and user interaction with the Website.
        </li>
      </ul>

      <h2>How We Use the Information</h2>

      <p>We use the information collected for the following purposes:</p>

      <ul>
        <li>To provide and maintain the Website.</li>
        <li>To improve and personalize your experience on our Website.</li>
        <li>
          To monitor and analyze usage and trends to improve the functionality
          and user experience of the Website.
        </li>
        <li>To serve relevant advertisements.</li>
      </ul>

      <h2>Third-Party Services</h2>

      <p>
        We may use third-party services such as Google Analytics. These
        third-party services may collect information sent by your browser as
        part of a web page request, such as cookies or your IP address.
      </p>

      <ul>
        <li>
          <strong>Google Analytics:</strong> Our Website uses Google Analytics,
          a web analytics service provided by Google, Inc. The information
          generated by the cookie about your use of our Website (including your
          IP address) will be transmitted to and stored by Google on servers in
          the United States. For more information on Google's privacy practices,
          please see
          <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google's Privacy Policy</a>.
        </li>
        <li>
          <strong>OpenAI Chat GPT:</strong>
          <p>Our Website uses OpenAI ChatGPT 3.5 Turbo if you choose to utilize the AI functionality.
            The responses generated by ChatGPT 3.5 Turbo on this website are based on patterns in
            data and do not reflect
            the opinions, beliefs, or values of Powerful Questions (Spero Autem LLC). The output from ChatGPT 3.5 Turbo is
            generated by a machine learning model, and as such, may not always be accurate, appropriate, or free from
            bias.</p>

          <p>While we strive to provide helpful and accurate information, Powerful Questions (Spero Autem LLC) makes no
            representations or
            warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or
            availability of the responses generated by ChatGPT 3.5 Turbo. Any reliance you place on such information is
            therefore strictly at your own risk.</p>

          <p>In no event will Powerful Questions (Spero Autem LLC) be liable for any loss or damage, including without
            limitation, indirect or
            consequential loss or damage, or any loss or damage whatsoever arising from the use of ChatGPT 3.5 Turbo on
            this
            website.</p>

          <p>Please note that the content generated by ChatGPT 3.5 Turbo may be subject to OpenAI's use-case policy and
            should be used in accordance with their guidelines.</p>
          <ul>
            <li><a href="https://openai.com/policies/usage-policies" target="_blank" rel="noopener">OpenAI Usage
                Policies</a>.</li>
            <li><a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener">OpenAI Privacy
                Policy</a></li>
            <li><a href="https://openai.com/policies/terms-of-use" target="_blank" rel="noopener">OpenAI Terms of Use</a>
            </li>
          </ul>
        </li>
      </ul>

      <h2>How You Can Control Cookies</h2>

      <p>
        Most web browsers allow you to control cookies through their settings
        preferences. However, if you limit the ability of websites to set
        cookies, you may worsen your overall user experience.
      </p>

      <p>
        To adhere to GDPR laws, Powerful Questions uses a consent for authorization
        model. By clicking "Accept All Cookies" on initial load, you agree to
        the use of Powerful Questions and third-party cookies to enhance your
        experience, analyse and measure your engagement with our content, and
        provide more relevant information which may include ads. Note that if
        you decline, NO cookies will be used. If you accept but you want to
        change your mind, please select the withdraw consent button below and
        your consent will be modified to NO.
      </p>

      <h2>Changes to this Privacy Policy</h2>

      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page and
        updating the “Last Updated” date at the top of this Privacy Policy. You
        are advised to review this Privacy Policy periodically for any changes.
      </p>

      <h2>Contact Us</h2>

      <p>
        If you have any questions about this Privacy Policy, please contact us
        at Spero Autem USA # +1 267-753-9235.
      </p>
    </div>
  </div>
  <div class="flex justify-center pt-4 pb-2" v-if="consentTrue">
    <button id="consent-button" class="btn btn-active btn-primary" @click="decline">
      Withdraw/Decline Consent
    </button>
  </div>
  <div class="flex justify-center pt-4 pb-2" v-else>
    <button id="consent-button" class="btn btn-active btn-primary" @click="consentToAll">
      Consent To Cookie Use
    </button>
  </div>
</template>

<script lang="ts" setup>
const consentAnalyticsCookies = useCookie<{ consent: boolean }>(
  "consentanalytics"
);
useHead({
  title: "Privacy Policy",
  meta: [
    {
      name: "description",
      content:
        "Your privacy is important to us. It is Powerful Questions&#39; policy to respect your privacy and comply with any applicable law and regulation regarding any personal information we may collect about you.",
    },
  ],
});

const consentToAll = () => {
  let consent_state = <HTMLInputElement>(
    document.getElementById("consent_modal")
  );
  consentAnalyticsCookies.value = { consent: true };
  location.reload();
};

const decline = () => {
  let consent_state = <HTMLInputElement>(
    document.getElementById("consent_modal")
  );
  consentAnalyticsCookies.value = { consent: false };
  location.reload();
};

const consentTrue = computed(() => {
  return (
    consentAnalyticsCookies.value &&
    consentAnalyticsCookies.value.consent == true
  );
});
</script>